schema_version: 2
name: togaf-shop
description: ''
statuses:
- Deferred
- Planned
- In Progress
- Completed
- Ongoing
- No Action
- Not Applicable
- Out-of-Scope
default_state: Planned
transitions:
  Completed:
  - In Progress
  Deferred:
  - Planned
  - Ongoing
  - No Action
  - Not Applicable
  - Out-of-Scope
  In Progress:
  - Completed
  - Planned
  - Ongoing
  - No Action
  - Not Applicable
  - Out-of-Scope
  No Action:
  - Planned
  Not Applicable:
  - Planned
  Ongoing:
  - In Progress
  - Planned
  Out-of-Scope:
  - Planned
  Planned:
  - In Progress
  - Deferred
  - Ongoing
  - No Action
  - Not Applicable
  - Out-of-Scope
displayed_states:
- Planned
- In Progress
- Completed
no_op_states:
- No Action
- Not Applicable
- Out-of-Scope
terminal_states:
- Completed
